site_name: Automated Documentation Demo

theme:
  name: material

extra_javascript:
  - javascripts/auto-reload.js

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Technical Documentation: doxygen/html/index.html